//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemRenLuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        public int ID { get; set; }
        public string PK_sMaGVID { get; set; }
        public string sTenGV { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public string sGioitinh { get; set; }
        public string sQuequan { get; set; }
        public string sChucvu { get; set; }
        public string FK_sMaKhoaID { get; set; }
        public string FK_sMaLopID { get; set; }
    }
}
