//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemRenLuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        public string PK_sMaKhoaID { get; set; }
        public string sTenKhoa { get; set; }
        public string sChunhiemkhoa { get; set; }
        public string sDiachi { get; set; }
        public string sDienthoai { get; set; }
    }
}
