//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemRenLuyen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyDiemRenLuyenEntities : DbContext
    {
        public QuanLyDiemRenLuyenEntities()
            : base("name=QuanLyDiemRenLuyenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DANHGIARENLUYEN> DANHGIARENLUYENs { get; set; }
        public virtual DbSet<DANHGIARENLUYENLOPTRUONG> DANHGIARENLUYENLOPTRUONGs { get; set; }
        public virtual DbSet<DANHGIARENLUYENTHAYCO> DANHGIARENLUYENTHAYCOes { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<HOCKY> HOCKies { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NAMHOC> NAMHOCs { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<SUKIEN> SUKIENs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THAMGIASUKIEN> THAMGIASUKIENs { get; set; }
    
        public virtual ObjectResult<dk_locsinhviendanhgia_Result> dk_locsinhviendanhgia(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgia_Result>("dk_locsinhviendanhgia", masvParameter);
        }
    
        public virtual ObjectResult<dk_locsinhviendanhgia1_Result> dk_locsinhviendanhgia1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgia1_Result>("dk_locsinhviendanhgia1", masvParameter);
        }
    
        public virtual ObjectResult<dk_locsinhviendanhgiagv_Result> dk_locsinhviendanhgiagv(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgiagv_Result>("dk_locsinhviendanhgiagv", masvParameter);
        }
    
        public virtual ObjectResult<dk_locsinhviendanhgiagv1_Result> dk_locsinhviendanhgiagv1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgiagv1_Result>("dk_locsinhviendanhgiagv1", masvParameter);
        }
    
        public virtual ObjectResult<dk_locsinhviendanhgialt_Result> dk_locsinhviendanhgialt(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgialt_Result>("dk_locsinhviendanhgialt", masvParameter);
        }
    
        public virtual ObjectResult<dk_locsinhviendanhgialt1_Result> dk_locsinhviendanhgialt1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dk_locsinhviendanhgialt1_Result>("dk_locsinhviendanhgialt1", masvParameter);
        }
    
        public virtual ObjectResult<ds_sinhviendanhgiaGV_Result> ds_sinhviendanhgiaGV(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ds_sinhviendanhgiaGV_Result>("ds_sinhviendanhgiaGV", malopParameter);
        }
    
        public virtual ObjectResult<ds_sinhviendanhgiaGV1_Result> ds_sinhviendanhgiaGV1(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ds_sinhviendanhgiaGV1_Result>("ds_sinhviendanhgiaGV1", malopParameter);
        }
    
        public virtual int ds_themdanhgiadiemrenluyen1(string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ds_themdanhgiadiemrenluyen1", masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int ds_themdanhgiadiemrenluyen2(string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ds_themdanhgiadiemrenluyen2", masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual ObjectResult<dsdanhgiadiemrenluyenGV1_Result> dsdanhgiadiemrenluyenGV1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dsdanhgiadiemrenluyenGV1_Result>("dsdanhgiadiemrenluyenGV1");
        }
    
        public virtual ObjectResult<eqeq_Result> eqeq(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<eqeq_Result>("eqeq", masvParameter);
        }
    
        public virtual ObjectResult<hienthidsdgsvdglt_Result> hienthidsdgsvdglt(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hienthidsdgsvdglt_Result>("hienthidsdgsvdglt", masvParameter);
        }
    
        public virtual ObjectResult<hienthidsdgsvdglt1_Result> hienthidsdgsvdglt1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hienthidsdgsvdglt1_Result>("hienthidsdgsvdglt1", masvParameter);
        }
    
        public virtual ObjectResult<sd_sinhviendanhgia_Result> sd_sinhviendanhgia(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sd_sinhviendanhgia_Result>("sd_sinhviendanhgia", malopParameter);
        }
    
        public virtual ObjectResult<sd_sinhviendanhgia1_Result> sd_sinhviendanhgia1(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sd_sinhviendanhgia1_Result>("sd_sinhviendanhgia1", malopParameter);
        }
    
        public virtual ObjectResult<Select_MaSV_Result> Select_MaSV(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_MaSV_Result>("Select_MaSV", maParameter);
        }
    
        public virtual ObjectResult<Select_SV_Result> Select_SV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_SV_Result>("Select_SV");
        }
    
        public virtual ObjectResult<sp_cho11_Result> sp_cho11(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cho11_Result>("sp_cho11", masvParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachSuKien_Result> sp_DanhSachSuKien(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSuKien_Result>("sp_DanhSachSuKien", masvParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachSuKien1_Result> sp_DanhSachSuKien1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSuKien1_Result>("sp_DanhSachSuKien1", masvParameter);
        }
    
        public virtual ObjectResult<sp_dssukien_Result> sp_dssukien(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dssukien_Result>("sp_dssukien", masvParameter);
        }
    
        public virtual ObjectResult<sp_hghghsk_Result> sp_hghghsk(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_hghghsk_Result>("sp_hghghsk", masvParameter);
        }
    
        public virtual ObjectResult<sp_laydiemsk_Result> sp_laydiemsk(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_laydiemsk_Result>("sp_laydiemsk", masvParameter);
        }
    
        public virtual ObjectResult<sp_laydiemsukien_Result> sp_laydiemsukien(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_laydiemsukien_Result>("sp_laydiemsukien", masvParameter);
        }
    
        public virtual ObjectResult<sp_laydiemsukien1_Result> sp_laydiemsukien1(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_laydiemsukien1_Result>("sp_laydiemsukien1", masvParameter);
        }
    
        public virtual ObjectResult<sp_LayDiemThamGiaHD_Result> sp_LayDiemThamGiaHD(string masv, Nullable<int> hocki, Nullable<int> nam)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var hockiParameter = hocki.HasValue ?
                new ObjectParameter("hocki", hocki) :
                new ObjectParameter("hocki", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDiemThamGiaHD_Result>("sp_LayDiemThamGiaHD", masvParameter, hockiParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_laysk_Result> sp_laysk(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_laysk_Result>("sp_laysk", masvParameter);
        }
    
        public virtual ObjectResult<sp_test_Result> sp_test(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_test_Result>("sp_test", masvParameter);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyen(string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyen", masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenGV(Nullable<int> iddglt, string masv, string magv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var iddgltParameter = iddglt.HasValue ?
                new ObjectParameter("iddglt", iddglt) :
                new ObjectParameter("iddglt", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenGV", iddgltParameter, masvParameter, magvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenGV1(Nullable<int> iddglt, string masv, string magv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var iddgltParameter = iddglt.HasValue ?
                new ObjectParameter("iddglt", iddglt) :
                new ObjectParameter("iddglt", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenGV1", iddgltParameter, masvParameter, magvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenGV2(Nullable<int> iddglt, string masv, string magv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var iddgltParameter = iddglt.HasValue ?
                new ObjectParameter("iddglt", iddglt) :
                new ObjectParameter("iddglt", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var magvParameter = magv != null ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenGV2", iddgltParameter, masvParameter, magvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenLT(Nullable<int> iddgsv, string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai)
        {
            var iddgsvParameter = iddgsv.HasValue ?
                new ObjectParameter("iddgsv", iddgsv) :
                new ObjectParameter("iddgsv", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenLT", iddgsvParameter, masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenLT1(Nullable<int> iddgsv, string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var iddgsvParameter = iddgsv.HasValue ?
                new ObjectParameter("iddgsv", iddgsv) :
                new ObjectParameter("iddgsv", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenLT1", iddgsvParameter, masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int sp_ThemDanhGiaDiemRenLuyenLT2(Nullable<int> iddgsv, string masv, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai, ObjectParameter id)
        {
            var iddgsvParameter = iddgsv.HasValue ?
                new ObjectParameter("iddgsv", iddgsv) :
                new ObjectParameter("iddgsv", typeof(int));
    
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhGiaDiemRenLuyenLT2", iddgsvParameter, masvParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter, id);
        }
    
        public virtual int sp_themthamgiasukien(string masv, Nullable<int> mask, string ghichu)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var maskParameter = mask.HasValue ?
                new ObjectParameter("mask", mask) :
                new ObjectParameter("mask", typeof(int));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themthamgiasukien", masvParameter, maskParameter, ghichuParameter);
        }
    
        public virtual int sp_themthamgiasukien1(string masv, Nullable<int> mask)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var maskParameter = mask.HasValue ?
                new ObjectParameter("mask", mask) :
                new ObjectParameter("mask", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themthamgiasukien1", masvParameter, maskParameter);
        }
    
        public virtual ObjectResult<sp_xemdiemrenluyen2_Result> sp_xemdiemrenluyen2(string masv, Nullable<int> phanbiet)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var phanbietParameter = phanbiet.HasValue ?
                new ObjectParameter("phanbiet", phanbiet) :
                new ObjectParameter("phanbiet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_xemdiemrenluyen2_Result>("sp_xemdiemrenluyen2", masvParameter, phanbietParameter);
        }
    
        public virtual int sp_updateDanhGiaDiemRenLuyenGV1(Nullable<int> id, Nullable<int> dihocdaydu, Nullable<int> kqhoctap, Nullable<int> cokhanvuotkho, Nullable<int> nckh, Nullable<int> tinhoc, Nullable<int> ngoaingu, Nullable<int> tongtieuchi1, Nullable<int> khongvipham, Nullable<int> giuginanninh, Nullable<int> giuginvesinh, Nullable<int> tongtieuchi2, Nullable<int> thamgiaHD, Nullable<int> llcanbomon, Nullable<int> llcapkhoa, Nullable<int> ktdoankhoa, Nullable<int> ktcaptruong, Nullable<int> ktcapcaohon, Nullable<int> tongtieuchi3, Nullable<int> khongviphamplnn, Nullable<int> cotinhthangiupdo, Nullable<int> thamgiadoi, Nullable<int> tongtieuchi4, Nullable<int> loptruong, Nullable<int> cansulop, Nullable<int> thanhtichdacbiet, Nullable<int> tongtieuchi5, Nullable<int> tongdiem, string xeploai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dihocdayduParameter = dihocdaydu.HasValue ?
                new ObjectParameter("dihocdaydu", dihocdaydu) :
                new ObjectParameter("dihocdaydu", typeof(int));
    
            var kqhoctapParameter = kqhoctap.HasValue ?
                new ObjectParameter("kqhoctap", kqhoctap) :
                new ObjectParameter("kqhoctap", typeof(int));
    
            var cokhanvuotkhoParameter = cokhanvuotkho.HasValue ?
                new ObjectParameter("cokhanvuotkho", cokhanvuotkho) :
                new ObjectParameter("cokhanvuotkho", typeof(int));
    
            var nckhParameter = nckh.HasValue ?
                new ObjectParameter("nckh", nckh) :
                new ObjectParameter("nckh", typeof(int));
    
            var tinhocParameter = tinhoc.HasValue ?
                new ObjectParameter("tinhoc", tinhoc) :
                new ObjectParameter("tinhoc", typeof(int));
    
            var ngoainguParameter = ngoaingu.HasValue ?
                new ObjectParameter("ngoaingu", ngoaingu) :
                new ObjectParameter("ngoaingu", typeof(int));
    
            var tongtieuchi1Parameter = tongtieuchi1.HasValue ?
                new ObjectParameter("tongtieuchi1", tongtieuchi1) :
                new ObjectParameter("tongtieuchi1", typeof(int));
    
            var khongviphamParameter = khongvipham.HasValue ?
                new ObjectParameter("khongvipham", khongvipham) :
                new ObjectParameter("khongvipham", typeof(int));
    
            var giuginanninhParameter = giuginanninh.HasValue ?
                new ObjectParameter("giuginanninh", giuginanninh) :
                new ObjectParameter("giuginanninh", typeof(int));
    
            var giuginvesinhParameter = giuginvesinh.HasValue ?
                new ObjectParameter("giuginvesinh", giuginvesinh) :
                new ObjectParameter("giuginvesinh", typeof(int));
    
            var tongtieuchi2Parameter = tongtieuchi2.HasValue ?
                new ObjectParameter("tongtieuchi2", tongtieuchi2) :
                new ObjectParameter("tongtieuchi2", typeof(int));
    
            var thamgiaHDParameter = thamgiaHD.HasValue ?
                new ObjectParameter("thamgiaHD", thamgiaHD) :
                new ObjectParameter("thamgiaHD", typeof(int));
    
            var llcanbomonParameter = llcanbomon.HasValue ?
                new ObjectParameter("llcanbomon", llcanbomon) :
                new ObjectParameter("llcanbomon", typeof(int));
    
            var llcapkhoaParameter = llcapkhoa.HasValue ?
                new ObjectParameter("llcapkhoa", llcapkhoa) :
                new ObjectParameter("llcapkhoa", typeof(int));
    
            var ktdoankhoaParameter = ktdoankhoa.HasValue ?
                new ObjectParameter("ktdoankhoa", ktdoankhoa) :
                new ObjectParameter("ktdoankhoa", typeof(int));
    
            var ktcaptruongParameter = ktcaptruong.HasValue ?
                new ObjectParameter("ktcaptruong", ktcaptruong) :
                new ObjectParameter("ktcaptruong", typeof(int));
    
            var ktcapcaohonParameter = ktcapcaohon.HasValue ?
                new ObjectParameter("ktcapcaohon", ktcapcaohon) :
                new ObjectParameter("ktcapcaohon", typeof(int));
    
            var tongtieuchi3Parameter = tongtieuchi3.HasValue ?
                new ObjectParameter("tongtieuchi3", tongtieuchi3) :
                new ObjectParameter("tongtieuchi3", typeof(int));
    
            var khongviphamplnnParameter = khongviphamplnn.HasValue ?
                new ObjectParameter("khongviphamplnn", khongviphamplnn) :
                new ObjectParameter("khongviphamplnn", typeof(int));
    
            var cotinhthangiupdoParameter = cotinhthangiupdo.HasValue ?
                new ObjectParameter("cotinhthangiupdo", cotinhthangiupdo) :
                new ObjectParameter("cotinhthangiupdo", typeof(int));
    
            var thamgiadoiParameter = thamgiadoi.HasValue ?
                new ObjectParameter("thamgiadoi", thamgiadoi) :
                new ObjectParameter("thamgiadoi", typeof(int));
    
            var tongtieuchi4Parameter = tongtieuchi4.HasValue ?
                new ObjectParameter("tongtieuchi4", tongtieuchi4) :
                new ObjectParameter("tongtieuchi4", typeof(int));
    
            var loptruongParameter = loptruong.HasValue ?
                new ObjectParameter("loptruong", loptruong) :
                new ObjectParameter("loptruong", typeof(int));
    
            var cansulopParameter = cansulop.HasValue ?
                new ObjectParameter("cansulop", cansulop) :
                new ObjectParameter("cansulop", typeof(int));
    
            var thanhtichdacbietParameter = thanhtichdacbiet.HasValue ?
                new ObjectParameter("thanhtichdacbiet", thanhtichdacbiet) :
                new ObjectParameter("thanhtichdacbiet", typeof(int));
    
            var tongtieuchi5Parameter = tongtieuchi5.HasValue ?
                new ObjectParameter("tongtieuchi5", tongtieuchi5) :
                new ObjectParameter("tongtieuchi5", typeof(int));
    
            var tongdiemParameter = tongdiem.HasValue ?
                new ObjectParameter("tongdiem", tongdiem) :
                new ObjectParameter("tongdiem", typeof(int));
    
            var xeploaiParameter = xeploai != null ?
                new ObjectParameter("xeploai", xeploai) :
                new ObjectParameter("xeploai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateDanhGiaDiemRenLuyenGV1", idParameter, dihocdayduParameter, kqhoctapParameter, cokhanvuotkhoParameter, nckhParameter, tinhocParameter, ngoainguParameter, tongtieuchi1Parameter, khongviphamParameter, giuginanninhParameter, giuginvesinhParameter, tongtieuchi2Parameter, thamgiaHDParameter, llcanbomonParameter, llcapkhoaParameter, ktdoankhoaParameter, ktcaptruongParameter, ktcapcaohonParameter, tongtieuchi3Parameter, khongviphamplnnParameter, cotinhthangiupdoParameter, thamgiadoiParameter, tongtieuchi4Parameter, loptruongParameter, cansulopParameter, thanhtichdacbietParameter, tongtieuchi5Parameter, tongdiemParameter, xeploaiParameter);
        }
    }
}
