//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfromQuetThe
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIARENLUYEN
    {
        public int ID { get; set; }
        public string FK_sMaSVID { get; set; }
        public int PK_sNamHoc { get; set; }
        public int PK_sHockyID { get; set; }
        public Nullable<int> DiHocDayDu { get; set; }
        public Nullable<int> KQHocTap { get; set; }
        public Nullable<int> CoGangVuotKho { get; set; }
        public Nullable<int> NCKH { get; set; }
        public Nullable<int> TinHoc { get; set; }
        public Nullable<int> NgoaiNgu { get; set; }
        public Nullable<int> TongTieuChi1 { get; set; }
        public Nullable<int> KhongViPham { get; set; }
        public Nullable<int> GiuGinAnNinh { get; set; }
        public Nullable<int> GiuVeSinh { get; set; }
        public Nullable<int> TongTieuChi2 { get; set; }
        public Nullable<int> ThamGiaHD { get; set; }
        public Nullable<int> LLCapboMon { get; set; }
        public Nullable<int> LLCapKhoa { get; set; }
        public Nullable<int> KTDoanKhoa { get; set; }
        public Nullable<int> KTCapTruong { get; set; }
        public Nullable<int> KTCapCaoHon { get; set; }
        public Nullable<int> TongTieuChi3 { get; set; }
        public Nullable<int> KhongViPhamPLNN { get; set; }
        public Nullable<int> CoTinhThanGiupDo { get; set; }
        public Nullable<int> ThamGiaDoi { get; set; }
        public Nullable<int> TongTieuChi4 { get; set; }
        public Nullable<int> LopTruong { get; set; }
        public Nullable<int> CanSuLop { get; set; }
        public Nullable<int> CacThanhTichDacBiet { get; set; }
        public Nullable<int> TongTieuChi5 { get; set; }
        public Nullable<int> iTongdiem { get; set; }
        public string sXeploai { get; set; }
        public Nullable<System.DateTime> dNgaylap { get; set; }
        public string TrangThai { get; set; }
    }
}
