//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfromQuetThe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public string PK_sMaLopID { get; set; }
        public string sTenLop { get; set; }
        public Nullable<int> sNambatdau { get; set; }
        public Nullable<int> sNamketthuc { get; set; }
        public string sCovanhoctap { get; set; }
    }
}
