//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfromQuetThe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUKIEN
    {
        public int ID { get; set; }
        public string TENSK { get; set; }
        public string DIADIEM { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public Nullable<int> DIEM { get; set; }
        public string TINHTRANG { get; set; }
        public string GHICHU { get; set; }
    }
}
