//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinfromQuetThe
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIASUKIEN
    {
        public int ID { get; set; }
        public string MASV { get; set; }
        public int MASK { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string GHICHU { get; set; }
    }
}
